'use client'

import { ScrollAnimation } from '@/components/ui/scroll-animation'
import { motion } from 'framer-motion'
import { Briefcase, Calendar } from 'lucide-react'

const experiences = [
    { role: 'Intern, Network & Communication Department', organization: 'Square InformatiX Limited', period: 'Aug 2026 – Present', description: 'Supporting enterprise networking, communication systems, IT infrastructure, and day-to-day technical operations.', current: true, type: 'industry' },
    { role: 'Quality Assurance Associate', organization: 'Acme AI', period: 'Jun 2026 – Present', description: 'Evaluating and improving AI-driven systems through structured testing, quality standards, and analysis workflows.', current: true, type: 'industry' },
    { role: 'Data Trainer', organization: 'SME Careers by SuperAnnotate', period: 'Jun 2026 – Present', description: 'Supporting consistent, accurate data annotation and evaluation workflows for AI model development.', current: true, type: 'industry' },
    { role: 'Senior Executive, Research & Development', organization: 'BRAC University Computer Club (BUCC)', period: 'Jun 2026 – Present', description: 'Managing engagement and recruitment while contributing to research, technical initiatives, and development activities.', current: true, type: 'leadership' },
    { role: 'Secretariat Associate, Specialized Committee', organization: 'IEEE BRACU Student Branch', period: '2026 – Present', description: 'Participating in technical events, research initiatives, and structured student knowledge-sharing programs.', current: true, type: 'research' },
    { role: 'Co-Founder', organization: 'Projukti Lipi', period: 'Aug 2025 – Present', description: 'Leading projects, community engagement, events, partnerships, operational strategy, and technical direction.', current: true, type: 'leadership' },
    { role: 'Junior Member, AI & Machine Vision', organization: 'BRACU Duburi', period: 'Mar 2025 – Present', description: 'Building vision systems and YOLO/OpenCV pipelines for autonomous underwater vehicle navigation and real-time decisions.', current: true, type: 'robotics' },
    { role: 'Executive, HR Department', organization: 'Robotics Club of BRAC University (ROBU)', period: 'Jun 2025 – Present', description: 'Supporting robotics projects through HR operations and effective cross-team collaboration.', current: true, type: 'leadership' },
    { role: 'Research Team Member', organization: 'IEEE Computer Society Bangladesh Chapter', period: '2025 – 2026', description: 'Contributed to technical documentation, collaborative research, and innovation programs.', current: false, type: 'research' },
    { role: 'Python Programming Intern', organization: 'CodeAlpha', period: 'Jan 2026 – Apr 2026', description: 'Built practical automation and data-handling projects while strengthening applied Python and problem-solving skills.', current: false, type: 'industry' },
    { role: 'Co-Team Lead', organization: 'OSHSHAROHI BRACU', period: 'Former role', description: 'Led cross-division coordination, system integration planning, risk mitigation, and competition readiness.', current: false, type: 'leadership' },
    { role: 'Junior Member, AI & Control Systems', organization: 'BRACU Alter', period: 'Apr 2025 – Dec 2025', description: 'Worked with ROS, Gazebo, OpenCV, YOLOv8, control theory, and AI navigation for rescue robotics.', current: false, type: 'robotics' },
    { role: 'Junior Member, Avionics Systems', organization: 'BRACU Diganta', period: '2025', description: 'Learned avionics and embedded programming, sensor integration, communication modules, and flight-data handling.', current: false, type: 'robotics' },
]

const typeColors: Record<string, string> = { industry: 'from-emerald-500/20 to-teal-500/20 border-emerald-500/30', leadership: 'from-amber-500/20 to-orange-500/20 border-amber-500/30', robotics: 'from-blue-500/20 to-cyan-500/20 border-blue-500/30', research: 'from-purple-500/20 to-pink-500/20 border-purple-500/30' }
const typeBadgeColors: Record<string, string> = { industry: 'bg-emerald-500/10 text-emerald-500', leadership: 'bg-amber-500/10 text-amber-500', robotics: 'bg-blue-500/10 text-blue-500', research: 'bg-purple-500/10 text-purple-500' }

export function ExperienceSection() {
    return <section id="experience" className="py-20 md:py-24 relative overflow-hidden"><div className="absolute inset-0 bg-gradient-to-b from-background via-card/30 to-background pointer-events-none" /><div className="container mx-auto px-4 sm:px-6 relative z-10"><ScrollAnimation className="text-center mb-12 md:mb-16"><h2 className="section-title">Experience</h2><p className="mt-8 text-muted-foreground max-w-2xl mx-auto text-sm md:text-lg">Industry, research, robotics, and leadership work with real-world impact.</p></ScrollAnimation><div className="grid md:grid-cols-2 gap-5 max-w-5xl mx-auto">{experiences.map((exp, index) => <ScrollAnimation key={`${exp.organization}-${exp.role}`} delay={Math.min(index * 0.04, 0.35)} direction="scale"><motion.div className={`h-full p-5 rounded-2xl border backdrop-blur-sm bg-gradient-to-br ${typeColors[exp.type]} transition-all group`} whileHover={{ scale: 1.015, boxShadow: '0 20px 40px rgba(0,0,0,.1)' }}><div className="flex items-start justify-between mb-4"><div className="flex gap-3 items-center"><div className="p-2.5 rounded-xl bg-card/80 text-primary"><Briefcase className="h-5 w-5" /></div><span className={`inline-flex px-2 py-0.5 rounded-full text-xs font-medium ${typeBadgeColors[exp.type]}`}>{exp.type}</span></div>{exp.current && <span className="flex items-center gap-1 px-2 py-0.5 rounded-full bg-green-500/10 text-green-500 text-xs font-medium"><span className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse" />Active</span>}</div><h3 className="text-lg font-bold text-foreground mb-1 group-hover:text-primary transition-colors">{exp.role}</h3><p className="text-primary font-medium mb-2">{exp.organization}</p><div className="flex items-center gap-1 text-sm text-muted-foreground mb-3"><Calendar className="h-3.5 w-3.5" />{exp.period}</div><p className="text-sm text-muted-foreground leading-relaxed">{exp.description}</p></motion.div></ScrollAnimation>)}</div></div></section>
}
