'use client'

import { useEffect, useState } from 'react'
import { useTheme } from 'next-themes'
import { Menu, Moon, Sun, X } from 'lucide-react'
import { AnimatePresence, motion } from 'framer-motion'
import { cn } from '@/lib/utils'
const navItems = ['About', 'Experience', 'Skills', 'Projects', 'Contact']
export function NavBar() { const { theme, setTheme } = useTheme(); const [mounted, setMounted] = useState(false); const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false); useEffect(() => { setMounted(true); const handler = () => setScrolled(window.scrollY > 24); window.addEventListener('scroll', handler, { passive: true }); return () => window.removeEventListener('scroll', handler) }, []); const close = () => setOpen(false); return <header className={cn('fixed inset-x-0 top-0 z-50 transition-all', scrolled ? 'border-b border-border bg-background/90 backdrop-blur py-3' : 'py-5')}><div className="container flex items-center justify-between"><a href="#home" className="font-mono text-sm tracking-[-.04em] font-semibold">MAHIR<span className="text-primary">/</span>DYAN</a><nav className="hidden lg:flex items-center gap-5">{navItems.map((item, index) => <a key={item} href={`#${item.toLowerCase()}`} className="font-mono text-[11px] uppercase tracking-[.08em] text-muted-foreground hover:text-primary"><span className="text-primary">0{index + 1}</span> {item}</a>)}<button onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')} className="ml-2 p-1.5 border border-border hover:border-primary" aria-label="Toggle theme">{mounted && theme === 'dark' ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}</button></nav><div className="flex lg:hidden gap-2"><button onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')} className="p-2 border border-border">{mounted && theme === 'dark' ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}</button><button onClick={() => setOpen(!open)} className="p-2 border border-border">{open ? <X className="h-4 w-4" /> : <Menu className="h-4 w-4" />}</button></div></div><AnimatePresence>{open && <motion.nav initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="lg:hidden mt-3 border-y border-border bg-background"><div className="container py-3 flex flex-col">{navItems.map((item, index) => <a onClick={close} key={item} href={`#${item.toLowerCase()}`} className="py-3 font-mono text-xs uppercase"><span className="text-primary">0{index + 1}</span> {item}</a>)}</div></motion.nav>}</AnimatePresence></header> }
