'use client'

import { ScrollAnimation, StaggerContainer, StaggerItem } from '@/components/ui/scroll-animation'
import { motion } from 'framer-motion'
import { Brain, Camera, Code2, ExternalLink, Github, Hand, Rocket, Scan, TrendingUp, Video } from 'lucide-react'

const projects = [
    { title: 'SignTutor 1.0', desc: 'Real-time, privacy-first ASL tutoring with webcam computer vision and Gemini-based corrective feedback.', icon: <Hand className="h-7 w-7" />, tags: ['Computer Vision', 'Gemini AI', 'ASL'], github: 'https://github.com/Iamm3taphorical/SignTutor-1.0', demo: 'https://www.kaggle.com/competitions/gemini-3/writeups/new-writeup-1765109533488', featured: true },
    { title: 'Freelance Pro', desc: 'Full-stack project management dashboard for clients, payments, and advanced analytics.', icon: <Code2 className="h-7 w-7" />, tags: ['Next.js', 'TypeScript', 'MySQL'], github: 'https://github.com/Iamm3taphorical/Freelance-Pro', featured: true },
    { title: 'DSE Smart Analytics', desc: 'Stock analysis and portfolio management platform with technical indicators and AI-driven insights.', icon: <TrendingUp className="h-7 w-7" />, tags: ['Analytics', 'AI', 'Finance'], github: 'https://github.com/Iamm3taphorical/DSE-Smart-Analytics', featured: true },
    { title: 'Smart Attendance & Identity', desc: 'Privacy-focused face-recognition attendance and identity tracking system for campus use.', icon: <Scan className="h-6 w-6" />, tags: ['Face Recognition', 'Python'], github: 'https://github.com/Iamm3taphorical/smart-attendance-system' },
    { title: 'CodeApproach Advisor', desc: 'LLM-powered coding-strategy assistant for selecting efficient algorithms and approaches.', icon: <Brain className="h-6 w-6" />, tags: ['LLM', 'Algorithms'], github: 'https://partyrock.aws/u/iamm3taphorical/oWvzUJXiY/CodeApproach-Advisor' },
    { title: 'Real-Time Object Detection', desc: 'Modular CLI detection system for webcam, video, and image streams.', icon: <Video className="h-6 w-6" />, tags: ['YOLOv8', 'CLI'], github: 'https://github.com/Iamm3taphorical/object-detection' },
    { title: 'Object Detection Pipeline', desc: 'Configurable batch image processing pipeline with labelled outputs and visualization grids.', icon: <Brain className="h-6 w-6" />, tags: ['YOLOv8', 'OpenCV'], github: 'https://github.com/Iamm3taphorical/Object-Detection-using-YOLOv8' },
    { title: 'Bottle Detection System', desc: 'Accessible YOLOv8 and OpenCV bottle-detection workflow with visual results.', icon: <Camera className="h-6 w-6" />, tags: ['YOLOv8', 'Matplotlib'], github: 'https://github.com/Iamm3taphorical/yolo-opencv-bottle-detection' },
    { title: 'Fragment', desc: 'Local-first Electron desktop app for organised multi-language code snippets.', icon: <Code2 className="h-6 w-6" />, tags: ['Electron', 'Desktop'], github: 'https://github.com/Iamm3taphorical/fragment' },
    { title: 'InstaBreaker', desc: 'Python social-media automation experiment with API workflow and rate-limit considerations.', icon: <Rocket className="h-6 w-6" />, tags: ['Python', 'Automation'], github: 'https://github.com/Iamm3taphorical/InstaBreaker' },
    { title: 'Smart Calc', desc: 'Responsive browser calculator with TypeScript, JavaScript, CSS, and core arithmetic logic.', icon: <Code2 className="h-6 w-6" />, tags: ['TypeScript', 'CSS'], github: 'https://github.com/Iamm3taphorical/smart-calc' },
]

export function ProjectsSection() {
    const featured = projects.filter((p) => p.featured); const others = projects.filter((p) => !p.featured)
    const ProjectCard = ({ project, small = false }: { project: typeof projects[number], small?: boolean }) => <motion.div className="group h-full bg-card/80 backdrop-blur-sm rounded-xl border border-border overflow-hidden hover:border-primary/50 transition-colors" whileHover={{ y: -4 }}><div className={`${small ? 'h-20' : 'h-28'} bg-gradient-to-br from-primary/20 via-accent/10 to-primary/5 flex items-center justify-center text-primary`}>{project.icon}</div><div className="p-4"><h3 className="font-bold text-foreground mb-2 group-hover:text-primary transition-colors">{project.title}</h3><p className="text-xs md:text-sm text-muted-foreground mb-3 line-clamp-2">{project.desc}</p><div className="flex flex-wrap gap-1.5 mb-3">{project.tags.map((tag) => <span key={tag} className="px-2 py-0.5 rounded-md bg-primary/10 text-xs font-medium text-primary">{tag}</span>)}</div><div className="flex gap-2"><a href={project.github} target="_blank" rel="noopener noreferrer" className="flex-1 py-2 px-3 bg-secondary/50 rounded-lg text-xs font-medium text-foreground hover:bg-secondary flex justify-center items-center gap-1"><Github className="h-4 w-4" />Code</a>{project.demo && <a href={project.demo} target="_blank" rel="noopener noreferrer" className="py-2 px-3 bg-primary rounded-lg text-xs font-medium text-primary-foreground"><ExternalLink className="h-4 w-4" /></a>}</div></div></motion.div>
    return <section id="projects" className="py-20 md:py-24 relative overflow-hidden"><div className="absolute inset-0 bg-gradient-to-b from-card/50 via-background to-card/50 pointer-events-none" /><div className="container mx-auto px-4 sm:px-6 relative z-10"><ScrollAnimation className="text-center mb-12 md:mb-16"><h2 className="section-title">Projects</h2><p className="mt-8 text-muted-foreground max-w-2xl mx-auto text-sm md:text-lg">AI, robotics, analytics, and full-stack software built for useful real-world problems.</p></ScrollAnimation><ScrollAnimation className="mb-6"><h3 className="text-xl font-bold text-primary flex items-center gap-2"><Rocket className="h-5 w-5" />Featured work</h3></ScrollAnimation><StaggerContainer className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6 mb-12">{featured.map((project) => <StaggerItem key={project.title}><ProjectCard project={project} /></StaggerItem>)}</StaggerContainer><ScrollAnimation className="mb-6"><h3 className="text-lg font-semibold text-muted-foreground">More projects</h3></ScrollAnimation><StaggerContainer className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{others.map((project) => <StaggerItem key={project.title}><ProjectCard project={project} small /></StaggerItem>)}</StaggerContainer><ScrollAnimation className="text-center mt-10"><a href="https://github.com/Iamm3taphorical?tab=repositories" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 px-5 py-2.5 bg-primary/10 border border-primary/20 rounded-xl text-primary text-sm font-medium hover:bg-primary/20"><Github className="h-4 w-4" />View All Repositories<ExternalLink className="h-3.5 w-3.5" /></a></ScrollAnimation></div></section>
}
